name: CI/CD for Node.js app

on:

  push:
    branches: [ '**' ]
    tags: [ '*\.*\.*' ]
  pull_request:
    branches: [ main ]

jobs:

  npm-start:
    name: Start Node.js App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v2
    - name: Use Node.js 14.18
      uses: actions/setup-node@v2
      with:
        node-version: 14.18
        cache: 'npm'
    - name: Install npm packages
      run: npm install
    - name: Start app
      run: npm start &
    - name: Send cURL Request to the Node.js App
      run: curl -i 0.0.0.0:8181/user

  build-production:
    name: Build Production App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v2
    - name: Use Node.js 14.18
      uses: actions/setup-node@v2
      with:
        node-version: 14.18
        cache: 'npm'
    - name: Install npm packages
      run: npm install
    - name: Build Production App Bundle
      run: npm run webpack-production
    - name: Upload Production App Bundle to Build Artefacts
      uses: actions/upload-artifact@v1
      with:
        name: app-bundle
        path: public/app-bundle.js

  run-unit-tests:
    name: Unit Tests
    needs: build-production
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at
        # https://nodejs.org/en/about/releases/
        os: [ubuntu-latest, ubuntu-18.04]
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: echo Running Jest Unit tests
    - run: npm test
    - name: Upload Test Report Artefact
      uses: actions/upload-artifact@v1
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.node-version }}
        path: public/test-results.xml
    - name: Upload Test Coverage Report Artefact
      uses: actions/upload-artifact@v1
      with:
        name: test-coverage-${{ matrix.os }}-${{ matrix.node-version }}
        path: public/coverage/clover.xml

  run-code-inspection:
    name: Code Inspection
    needs: build-production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v2
    - name: Use Node.js 14.18
      uses: actions/setup-node@v2
      with:
        node-version: 14.18
        cache: 'npm'
    - run: npm install
    - name: Run ESLint Scan on app sourcecode
      run: npm run eslint-scan
    - name: Generate ESLint Report from app sourcecode scan
      run: npm run eslint-report
    - name: Upload Linter Report Artefact
      uses: actions/upload-artifact@v1
      with:
        name: linter-results
        path: public/linter-results.xml

  generate-jsdoc:
    name: Generate Documentation
    needs: [run-unit-tests, run-code-inspection]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v2
    - name: Use Node.js 14.18
      uses: actions/setup-node@v2
      with:
        node-version: 14.18
        cache: 'npm'
    - run: npm install
    - run: npm run jsdoc
    - name: Upload JSDoc documentation
      uses: actions/upload-artifact@v1
      with:
        name: jsdoc-sourcecode-documentation
        path: public/jsdoc

  create-github-release:
    name: Create GitHub Release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: generate-jsdoc
    runs-on: ubuntu-latest
    steps:
    - name: Parse release version from git tag
      run: echo "release-version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Print out parsed release version
      run: echo Parsed release version is:${{ env.release-version }}
    - name: Download Production Build Artefact
      uses: actions/download-artifact@v1
      with:
        name: app-bundle
        path: public
    - name: Delete Production Build Artefact
      uses: geekyeggo/delete-artifact@v1
      with:
        name: app-bundle
    - name: Rename Production Build Artefact by inserting release version
      run: mv "public/app-bundle.js" "public/app-bundle-v${{ env.release-version }}.js"
    - name: Upload Renamed Production Build Artefact
      uses: actions/upload-artifact@v1
      with:
        name: app-bundle-v${{ env.release-version }}
        path: public/app-bundle-v${{ env.release-version }}.js
    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        name: Release v${{ env.release-version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.release-version }}
        artifacts: 'public/app-bundle-v${{ env.release-version }}.js'
        allowUpdates: true
        omitBody: true
        removeArtifacts: true

  dockerize:
    runs-on: ubuntu-latest
    needs: build-production
    name: Dockerize Production App
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v2
      - name: Download Production Build Artefact
        uses: actions/download-artifact@v1
        with:
          name: app-bundle
          path: public
      - name: Build Docker Image from Dockerfile
        run: docker build . --tag express-js-app:14.18
      - name: Create and run Docker Container from Docker Image
        run: docker run --name express-js-app-container --detach --publish 45678:8181 --tty express-js-app:14.18
      - name: Sleep 5 seconds (wait till Express.js app is running)
        run: sleep 5s
      - name: Send a cURL request to the Docker container
        run: curl -i 0.0.0.0:45678/user
      - name: Stop the Docker Container
        run: docker stop express-js-app-container
      - name: Wait until Docker Container is down
        run: docker wait express-js-app-container
